### PR TITLE
Add BoneJ

### PR DESCRIPTION
**Pull request by rimadoma**
* Adds BoneJ icon
* Adds BoneJ link

**Not ready to merge!**

What do I need to do to get the link working the same way as the others?

### CODE REVIEW

**Comment by ctrueden** [comment]
@rimadoma Nice!

> What do I need to do to get the link working the same way as the others?

Each link works in one of two ways:

1. A special job builds javadocs daily and pushes them to the appropriate subfolder of this repository. E.g. the [fiji-javadoc](https://github.com/fiji/fiji-javadoc) job keeps the `Fiji/` subtree up to date. You would make a `bonej-javadoc` repository responsible for doing that for `BoneJ/`. I'd file a PR there adding the encrypted SSH deploy key.

2. You build and publish the BoneJ javadocs somewhere else, however you please. I add a proxy/reverse-proxy setting to serve your javadoc URL transparently whenever `https://javadoc.scijava.org/BoneJ` is accessed. If your site goes down, the BoneJ javadocs go down. This is the technique we use for most of the icons—whatever is not present directly here in this repository.

**Comment by rimadoma** [comment]
@ctrueden Okay, I chose option 1 and created https://github.com/bonej-org/bonej-javadoc. I think I've got the pom and cron job set up.

**Comment by ctrueden** [comment]
@rimadoma Great, thanks! :-) But I got it backwards. I need _you_ to generate the SSH keypair and encrypt the private key using `travis encrypt-file`. Commit it as `.travis/javadoc.scijava.org.enc` to the `bonej-org/bonej-javadoc` repository. Then paste me the corresponding PUBLIC key on Gitter and I will add that as a deploy key to the `scijava/javadoc.scijava.org` repository.

**Comment by rimadoma** [comment]
I have now created the `javadoc.scijava.org.enc` file, and sent you the public key on Gitter. I didn't quite understand how to create the _key_ and _iv_ environment variables. I ran travis encrypt KEY = ***, and then added the result to both variables, since it seemed to be the same value in `scijava-javadoc`.

**Comment by rimadoma** [comment]
The environment variables are now sorted. I think everything's ready in my end, unless I needed to change the `secure` value in `.travis.yml`?

**Comment by ctrueden** [comment]
There was an extra `javadoc.scijava.org.enc` in the base directory, which I removed. And the `.travis/build.sh` needed the executable bit set. There was then something wrong with the decryption, so I guess things were not registered properly. I generated a new SSH keypair, encrypted it, and updated the key/iv variables according to what `travis encrypt-file` spat out. And now things appear to be up and running. We'll see if the job stalls (as Travis jobs have been wont to do lately) or completes. If it stalls, I'll just restart it.

**Comment by ctrueden** [comment]
It worked! :tada:

**Comment by rimadoma** [comment]
@ctrueden Thanks for all your help, and patience :)

**Pull request merged**
